export { GitHubIcon } from './GitHubIcon'
export { TelegramIcon } from './TelegramIcon'
export { TwitterIcon } from './TwitterIcon'
export { TwitterIcon2 } from './TwitterIcon2'
export { ArrowRightIcon } from './ArrowRightIcon'
export { CopyClipboardIcon } from './CopyClipboardIcon'
export { DiscordIcon } from './DiscordIcon'
