export const URLS = {
  ROOT: '/',
  COLLECTION: '/collection',
  SANDBOX: 'https://sandbox.frakt.art',
  FRAKTION: 'https://fraktion.art',
  MARKETPLACE: '/marketplace',
  STAKE: '/stake',
  STAKING_FRKT: '/stake-frkt',
  STAKING_NFT: '/stake-nft',
  STAKING_NFT_CREATE: `/stake-nft/create`,
  STAKING_NFT_UNSTAKE: '/stake-nft/unstake',
  STAKING_NFT_HARVEST: '/stake-nft/harvest',
  WALLET: '/wallet',
  RARITY: '/rarity',
  PAGE_404: '/404',
};
